---
- name: Configure `mastodon.me.uk`
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - group_vars/{{ env }}/all.yaml

  roles:
    - role: measures
    - role: domain_blocks
