---
- name: URI Test
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Hit `measures` endpoint
      uri:
        url: "{{ instance_url }}/api/v1/admin/measures"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'MASTODON_TOKEN') }}"
        method: POST
        body_format: json
        status_code:
          - 200
      register: response

    - debug:
        var: response
