---

- name: Read CSV
  community.general.read_csv:
    path: "{{ blocks_file }}"
  register: domain_blocks

- name: Block domains
  loop: "{{ domain_blocks.list }}"
  loop_control:
    loop_var: domain
  ansible.builtin.uri:
    url: "{{ instance_url }}/api/v1/admin/domain_blocks"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'MASTODON_DOMAIN_BLOCK_TOKEN') }}"
    method: POST
    body_format: json
    body: "{{ domain }}"
    status_code:
      - 200
      - 422

- name: Retrieve blocked domains
  ansible.builtin.uri:
    url: "{{ instance_url }}/api/v1/admin/domain_blocks"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ lookup('ansible.builtin.env', 'MASTODON_READ_ONLY_TOKEN') }}"
    method: GET
    body_format: json
    status_code:
      - 200
  register: response

- name: Show blocked domains
  ansible.builtin.debug:
    var: response.json
